name: matrl-test
dependencies:
    - python=3.7
    - numpy 
    - openmpi
    - matplotlib
    - tensorflow
    - cloudpickle =1.2.1
    - ipython
    - joblib
    - matplotlib=3.1.1
    - mpi4py
    - numpy
    - pandas
    - pytest
    - psutil
    - scipy
    - seaborn=0.8.1
    - tensorflow>=1.8.0,<2.0
    - tqdm
    - pyyaml